# JDemetra+-Quickstart for the graphical user interface (GUI) { .unnumbered #quickstart}


The sections below will briefly describe the steps involved in installing JDemetra+, uploading the data, perform seasonal adjustment and export the data. The guide is intended for a novice user, hence it does not dwell on the theoretical aspects of seasonal adjustment. 

-   How to install JDemetra+

-   How to get data into JDemetra+

-   How to do seasonally adjust your data

-   How to export the data

## JDemetra+ installation

Easy breezy

### The structure of the software

Workspace, Providers, plug-ins

## Data import

From Excel


## Default seasonal adjustment

| Method      | Name in GUI   | Details                                                                                                                                              |
|-------------|---------------|------------------------------------------------------------------------------------------------------------------------------------------------------|
| Tramo-Seats | tramoseats    | Decomposition of the time series based on RegARIMA modelling                                                                                         |
| X-13-ARIMA  | x13           | Combination of RegARIMA modelling for calendar effect and moving average based decomposition (X-11) for the extraction of the seasonal effect        |

Full documentation of the Seats method can be found [here](https://jdemetra-new-documentation.netlify.app/m-x11-decomposition), while all details on X-11 can be found [here](https://jdemetra-new-documentation.netlify.app/m-x11-decomposition).


## Export the data

To export the data you can choose xlsx, csv


